Task 6
dgrimaliuc/tekwill-qa-automation pull request #72
Opened 2023-06-22 21:36 UTC by Raetskaya

task 6

2023-06-24 17:43 UTC, dgrimaliuc requested changes
PLease resolve conflicts 
![image](https://github.com/dgrimaliuc/tekwill-qa-automation/assets/116957079/e9640ca8-19dc-451f-8bc7-0eb0a2802998)

2023-06-26 14:11 UTC, dgrimaliuc-crunchyroll approved these changes

2023-06-26 14:11 UTC, dgrimaliuc-crunchyroll commented on src/main/java/ana_raetcaia/Book.java
> +    private final String name;
not sure if it is right to make all fields final

2023-06-26 14:12 UTC, dgrimaliuc approved these changes

2023-06-26 14:49 UTC, merged